title: CEEDS Tool documentation
description: CEEDS Tool Version 4 documentation
theme: just-the-docs/just-the-docs

# Theme settings:
site_author: thopri
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
